version: '3'

services:
  db:
    image: mysql:8
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: project
      MYSQL_USER: projectuser
      MYSQL_PASSWORD: projectuserpass
    restart: always

  web:
    container_name: web
    build: ./web
    volumes:
      - ./web:/opt/project
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  smtp:
    container_name: smtp
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025
      - 1025:1025
    restart: always
